clustering:
  cluster_on_correlation: true
  number_of_clusters: 60
  parameters: searching
  range_n_clusters: 0
  strategy: Hierarchical
dataset:
  input_folder: data/
  label_column: label_lung_small
  name: lung_small
  scaler: standard
filters:
  autoencoder_parameters:
    AE_name: LinearAE
    epochs: 100
    lr: 0.001
    n_layers:
    - 1
    - 2
    - 3
    - 4
  filter_type: AE
  medoid_parameters:
    distance_metric: euclidean
output:
  logs_folder: Model_results/FeSCAE/results_FeSCAE_lung_small/output_lung_small_60_hierarchical
  output_folder: Model_results/FeSCAE/results_FeSCAE_lung_small/output_lung_small_60_hierarchical
