dataset:
  name: "Leukemia"
  input_folder: "Raw_Datasets/Leukemia_ttft"
  label_column: "TTFT"
  scaler: "standard"

output:
  output_folder: "prova_output"
  logs_folder: "prova_output"

clustering:
  strategy: "KMeans"
  cluster_on_correlation: True
  number_of_clusters: 20
  parameters: "searching"
  # Se vuoi passare un dizionario, sostituisci sopra con:
  # parameters:
  #   distance_metric: "mahalanobis"
  #   linkage_method: "single"

filters:
  filter_type: 'AE' #or Medoid
  autoencoder_parameters:
    lr: 0.001
    epochs: 100
    AE_name: 'LinearAE'
  medoid_parameters:
    distance_metric: "euclidean"




    