dataset:
  name: "Colon" #Colon, Prostate, Lymphoma, LeukemiaALLAML, LeukemiaTTFT, Leukemia, TOX-171, GLI-85
  input_folder: "Raw_Datasets/"
  label_column: "label_colon"
  scaler: "standard"

output:
  output_folder: "output_colon_10_hierarchical"
  logs_folder: "output_colon_10_hierarchical"

clustering:
  strategy: "Hierarchical"
  cluster_on_correlation: True
  number_of_clusters: 10
  range_n_clusters: 0
  parameters: "searching"
  # Se vuoi passare un dizionario, sostituisci sopra con:
  # parameters:
  #   distance_metric: "mahalanobis"
  #   linkage_method: "single"

filters:
  filter_type: 'AE' #or Medoid
  autoencoder_parameters:
    lr: 0.001
    epochs: 100
    AE_name: 'LinearAE'
    n_layers: [1,2,3,4]
  medoid_parameters:
    distance_metric: "euclidean"




    