clustering:
  cluster_on_correlation: true
  number_of_clusters: 40
  parameters: searching
  range_n_clusters: 0
  strategy: KMeans
dataset:
  input_folder: data/
  label_column: label_pixraw10p
  name: pixraw10P
  scaler: standard
filters:
  autoencoder_parameters:
    AE_name: LinearAE
    epochs: 100
    lr: 0.001
    n_layers:
    - 1
    - 2
    - 3
    - 4
  filter_type: AE
  medoid_parameters:
    distance_metric: euclidean
output:
  logs_folder: Model_results/FeSCAE/results_FeSCAE_pixraw10p/output_pixraw10p_40_kmeans
  output_folder: Model_results/FeSCAE/results_FeSCAE_pixraw10p/output_pixraw10p_40_kmeans
